version: '3.7'
services:
  # Each container we'll create will have its own service block where we define
  # container name, location of the build and the dockerfile, env file, ports & volumes
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: unless-stopped
    expose: 
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      -  inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    restart: on-failure
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: '/home/tfiguero/data/mariadb'
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/tfiguero/data/wordpress'
      o: bind

networks:
  inception:
    driver: bridge
